data:
  trainpath: '~/ros2_ws/dataset/'  # Path to the dataset (make sure to use the absolute path)
  batch_size: 256  # Adjust as needed based on your memory constraints
  num_workers: 4  # Number of workers for loading data
  valid_ratio: 0.2  # Ratio for validation set

model:
  class: ResNet18  # Model class, using ResNet18 (could be a simple model for regression)
  num_classes: 1  # Single output class for regression (no multiple classes)
  pretrained: True  # Use a pre-trained model (useful for transfer learning)
  output_dim: 1  # Output dimension is 1 for regression tasks (single continuous value)

optim:
  algo: Adam  # Optimizer to use
  params:
    lr: 0.001  # Learning rate for Adam optimizer

loss:
  type: MSELoss  # Mean Squared Error Loss (common for regression tasks)

training:
  epochs: 20  # Number of epochs for training

logging:
  logdir: "./logs"  # Directory to save logs
  # wandb:  # Uncomment these lines to enable logging with Weights & Biases
  #   project: sample_project
  #   entity: sample_entity

scheduler:
  step_size: 10  # Epochs after which the learning rate will be reduced
  gamma: 0.1  # Factor by which the learning rate will be reduced (e.g., lr = lr * gamma)

